name: Electron App Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Electron Builder
        uses: paneron/action-electron-builder@v1.8.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_package_manager_install: false
          package_manager: npm
          release: true
          package_root: .
          build_script_name: build
          skip_build: false
          use_vue_cli: false
          max_attempts: 1
